apiVersion: v1
kind: Service
metadata:
  name: autoscale-backend
  namespace: autoscale
spec:
  selector:
    app: autoscale-backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  