apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autoscale-backend-monitor
  namespace: autoscale
spec:
  selector:
    matchLabels:
      app: autoscale-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
