apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-frontend
  namespace: autoscale
  labels:
    app: autoscale-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale-frontend
  template:
    metadata:
      labels:
        app: autoscale-frontend
    spec:
      containers:
        - name: frontend
          image: harishx64/autoscale-frontend:latest
          ports:
            - containerPort: 80

          # Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5

          # Resource limits (REQUIRED for HPA)
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
