apiVersion: v1
kind: Service
metadata:
  name: autoscale-frontend
  namespace: autoscale
spec:
  selector:
    app: autoscale-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
